# -*- coding: utf-8 -*-
"""House Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmOcqFnnnYEIOmwDqNx2aafl0yhSNy-6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LinearRegression , SGDRegressor,Ridge,Lasso
from sklearn.metrics import mean_squared_error,r2_score
import statsmodels.api as sm

df = pd.read_csv('Housing.csv')
df.head()

df.shape

df.describe()

df.describe(include='object')

df.info()

"""### EDA & Visulization"""

sns.histplot(data=df,x='price',color='#8A244B')
plt.vlines(x=df['price'].mean(),ymin=30,ymax=85,color='red',linestyle='--')
plt.vlines(x=df['price'].median(),ymin=30,ymax=85,color='green',linestyle='--')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Price Distribution')
plt.legend(['Mean','Median'])
plt.show()
# Distribution is right skewed
# there are some outlayers

sns.boxplot(data=df,x='price',color='#8A244B')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Price Distribution')
plt.show()

min_price=df['price'].min()
max_price=df['price'].max()
Q1=df['price'].quantile(0.25)
Q3=df['price'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-(1.5*IQR)
upper_bound=Q3+(1.5*IQR)
print('min_price:',min_price)
print('max_price:',max_price)
print('Q1:',Q1)
print('Q3:',Q3)
print('IQR:',IQR)

df[df['price']>upper_bound]
# 14 house are is outlayers

sns.boxplot(data=df,x='area',color='#8A244B')
plt.xlabel('Area')
plt.ylabel('Frequency')
plt.title('Area Distribution')
plt.show()
# some outlayers

df.corr(numeric_only=True)['price']
# relationship between price and other features

sns.heatmap(df.corr(numeric_only=True),annot=True,cmap='coolwarm')
plt.show()
# all feature affect in the price
# big correlation is area

fig,ax=plt.subplots(2,3,figsize=(15,10))

sns.scatterplot(data=df,x='area',y='price',color='#8A244B',ax=ax[0,0])
ax[0,0].set_xlabel('Area')
ax[0,0].set_ylabel('Price')
ax[0,0].set_title('Area vs Price')

sns.scatterplot(data=df,x='bedrooms',y='price',color='#8A244B',ax=ax[0,1])
ax[0,1].set_xlabel('Bedrooms')
ax[0,1].set_ylabel('Price')
ax[0,1].set_title('Bedrooms vs Price')

sns.scatterplot(data=df,x='bathrooms',y='price',color='#8A244B',ax=ax[0,2])
ax[0,2].set_xlabel('Bathrooms')
ax[0,2].set_ylabel('Price')
ax[0,2].set_title('Bathrooms vs Price')

sns.scatterplot(data=df,x='stories',y='price',color='#8A244B',ax=ax[1,0])
ax[1,0].set_xlabel('Stories')
ax[1,0].set_ylabel('Price')
ax[1,0].set_title('Stories vs Price')

sns.scatterplot(data=df,x='parking',y='price',color='#8A244B',ax=ax[1,1])
ax[1,1].set_xlabel('Parking')
ax[1,1].set_ylabel('Price')
ax[1,1].set_title('Parking vs Price')

plt.tight_layout()
plt.show()

median_prices_for_num_bedrooms = pd.pivot_table(data=df,index='bedrooms',values='price',aggfunc='median')

x=median_prices_for_num_bedrooms.values.ravel()
y=median_prices_for_num_bedrooms.index

plt.pie(x=x,labels=y,autopct='%1.1f%%')
plt.title('Median Prices for Different Number of Bedrooms')
plt.show()

median_prices_for_num_bathrooms = pd.pivot_table(data=df,index='bathrooms',values='price',aggfunc='median')
x=median_prices_for_num_bathrooms.values.ravel()
y=median_prices_for_num_bathrooms.index

plt.pie(x=x,labels=y,autopct='%1.1f%%')
plt.title('Median Prices for Different Number of Bathrooms')
plt.show()

sns.boxplot(data=df,x='mainroad',y='price',color='#8A244B')
plt.xlabel('Mainroad')
plt.ylabel('Price')
plt.title('Mainroad vs Price')
plt.show()

sns.boxplot(data=df,x='airconditioning',y='price',color='#8A244B')
plt.xlabel('Airconditioning')
plt.ylabel('Price')
plt.title('Airconditioning vs Price')
plt.show()

g=sns.barplot(data=df,x='prefarea',y='price',color='#8A244B')
plt.xlabel('Prefarea')
plt.ylabel('Price')
plt.title('Prefarea vs Price')
plt.show()

sns.boxplot(data=df,x='furnishingstatus',y='price',palette='rocket')
plt.xlabel('Furnishingstatus')
plt.ylabel('Price')
plt.title('Furnishingstatus vs Price')
plt.show()

sns.scatterplot(
    data=df,
    x='area',
    y='price',
    hue='furnishingstatus'
)
plt.xlabel('Area')
plt.ylabel('Price')
plt.title('Area vs Price')
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df,
    x='area',
    y='price',
    hue='airconditioning'
)
plt.title("Area vs Price (Air Conditioning )")
plt.show()

X=df.drop('price',axis=1)
y=df['price']

num_cul=[col for col in X.columns if X[col].dtype!='object']
cat_cul=[col for col in X.columns if X[col].dtype=='object']

"""### Feature Selection"""

selector=sm.OLS(y,X[num_cul])
selector=selector.fit()
selector.summary()

# all feature --->  p-value < 0.05
# there are relationship

"""### Data Preprocessing"""

y=np.log1p(y)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

imputer=SimpleImputer(strategy='median')

X_train_num_fill=imputer.fit_transform(X_train[num_cul])
X_test_num_fill=imputer.transform(X_test[num_cul])


X_train_cat_fill = SimpleImputer(strategy='most_frequent').fit_transform(X_train[cat_cul])
X_test_cat_fill = SimpleImputer(strategy='most_frequent').fit_transform(X_test[cat_cul])

encoder=OneHotEncoder(sparse_output=False,drop='first')
X_train_encoded=encoder.fit_transform(X_train_cat_fill)
X_test_encoded=encoder.transform(X_test_cat_fill)

standard=StandardScaler()
X_train_num_scaled=standard.fit_transform(X_train_num_fill)
X_test_num_scaled=standard.transform(X_test_num_fill)

X_train_final=np.concatenate((X_train_encoded,X_train_num_scaled),axis=1)
X_test_final=np.concatenate((X_test_encoded,X_test_num_scaled),axis=1)

"""###Train the model with LinearRegression

"""

LR_model=LinearRegression()
LR_model.fit(X_train_final,y_train)

scores=cross_val_score(LR_model,X_train_final,y_train,cv=5,scoring='neg_mean_squared_error')

mse_scores=-scores
rmse_scores=np.sqrt(mse_scores)

print('MSE',mse_scores)
print('RMSE',rmse_scores)
print('Avg_MSE',np.average(mse_scores))
print('Mean RMSE',rmse_scores.mean())
print('----------------------------')

r2_scores=cross_val_score(LR_model,X_train_final,y_train,cv=5,scoring='r2')

print('R2',r2_scores)
print('Avg_R2',np.average(r2_scores))
